[workspace]
resolver = "3"
members = ["sn8flash-lib", "sn8flash", "sn8flash-gui"]
default-members = ["sn8flash"]

[workspace.package]
version = "1.0.8"
edition = "2024"
authors = ["Silica Gel <silicagel777@proton.me>"]
repository = "https://github.com/silicagel777/SN8Flash"
documentation = "https://github.com/silicagel777/SN8Flash"
homepage = "https://github.com/silicagel777/SN8Flash"
categories = ["embedded", "hardware-support", "development-tools::debugging"]
keywords = ["embedded", "Sonix", "SN8F", "SN8"]
readme = "README.md"
license = "MIT"

[workspace.lints.rust]
unused_must_use = "deny"
